import {database} from '../../../db';
import {getViewer} from '../../supabase-auth';
import {freshState,chessPosition,checkMove,words} from '../../game-rules';
export const dynamic='force-dynamic';
class Problem extends Error{constructor(message:string,public status=400){super(message)}}
const json=(d:unknown,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'no-store'}});
const kinds=['island','chess','checkers','guess','drawing'];
const str=(v:unknown,min:number,max:number)=>{if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)throw new Problem('Invalid text length.');return v.trim()};
const finite=(n:unknown,min:number,max:number)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)throw new Problem('Invalid position.');return n};
async function all(q:string,...a:any[]){return (await database().prepare(q).bind(...a).all<any>()).results}
async function who(){const u=await getViewer();if(!u)throw new Problem('Sign in to play.',401);const p=await database().prepare('SELECT id,name,color FROM profiles WHERE id=?').bind(u.userId).first<any>();if(!p)throw new Problem('Create your player profile first.',409);return p}
async function member(room:string,uid:string){const p=await database().prepare('SELECT * FROM game_players WHERE room_id=? AND user_id=? AND seen_at>?').bind(room,uid,Date.now()-75000).first<any>();if(!p)throw new Problem('Join this game room first.',403);return p}
async function roomData(room:string){const r=await database().prepare('SELECT * FROM game_rooms WHERE id=?').bind(room).first<any>();if(!r)throw new Problem('Game room not found.',404);return r}
async function event(room:string,uid:string,kind:string,payload:unknown){await database().prepare('INSERT INTO game_events(room_id,user_id,kind,payload,created_at) VALUES(?,?,?,?,?)').bind(room,uid,kind,JSON.stringify(payload),Date.now()).run()}
async function update(r:any,s:any){const q=await database().prepare('UPDATE game_rooms SET state=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(s),r.id,r.version).run();if(!q.meta.changes)throw new Problem('Another player acted first. Refreshing the room; try again.',409)}
function viewState(r:any,uid:string){const s=JSON.parse(r.state);if(r.kind==='guess'&&s.drawer!==uid&&!s.revealed&&Date.now()-s.started<90000){s.wordLength=s.word.length;delete s.word;}return s}
function problem(e:unknown){if(e instanceof Problem)return json({error:e.message},e.status);console.error('Game room request failed',e instanceof Error?e.message:String(e),e instanceof Error&&e.cause instanceof Error?e.cause.message:'');return json({error:'Game connection interrupted. Please retry.'},503)}
export async function GET(request:Request){try{const p=await who(),url=new URL(request.url),op=url.searchParams.get('op')||'list',now=Date.now();
 if(op==='list'){const q=(url.searchParams.get('q')||'').slice(0,80);return json({rooms:await all(`SELECT g.id,g.name,g.kind,g.owner,p.name AS owner_name,(SELECT COUNT(*) FROM game_players WHERE room_id=g.id AND seen_at>?) AS count FROM game_rooms g JOIN profiles p ON p.id=g.owner WHERE instr(lower(g.name),lower(?))>0 ORDER BY g.created_at DESC LIMIT 100`,now-75000,q)});}
 const room=str(url.searchParams.get('room'),1,100);await member(room,p.id);const r=await roomData(room),after=Number(url.searchParams.get('after')||0),signalAfter=Number(url.searchParams.get('signalAfter')||0);if(!Number.isSafeInteger(after)||after<0||!Number.isSafeInteger(signalAfter)||signalAfter<0)throw new Problem('Invalid cursor.');
 const players=await all('SELECT g.user_id,g.slot,g.x,g.y,g.look,g.voice,p.name,p.color FROM game_players g JOIN profiles p ON p.id=g.user_id WHERE g.room_id=? AND g.seen_at>? ORDER BY g.slot',room,now-75000);
 const events=await all(`SELECT e.id,e.user_id,e.kind,e.payload,e.created_at,p.name FROM game_events e JOIN profiles p ON p.id=e.user_id WHERE e.room_id=? AND e.id>? ORDER BY e.id ASC LIMIT 500`,room,after);
 const signals=await all('SELECT id,sender,payload FROM voice_signals WHERE room_id=? AND recipient=? AND id>? AND created_at>? ORDER BY id LIMIT 100',room,p.id,signalAfter,now-120000);
 return json({room:{id:r.id,name:r.name,kind:r.kind,owner:r.owner,version:r.version},state:viewState(r,p.id),players:players.map(v=>({...v,look:JSON.parse(v.look)})),events:events.map(e=>({...e,payload:JSON.parse(e.payload)})),signals:signals.map(e=>({...e,payload:JSON.parse(e.payload)}))});
 }catch(e){return problem(e)}}
export async function POST(request:Request){try{if(request.headers.get('origin')!==new URL(request.url).origin)throw new Problem('Use Pixel Relay to play.',403);const raw=await request.text();if(raw.length>24000)throw new Problem('Request too large.',413);const b=JSON.parse(raw),p=await who(),db=database(),now=Date.now();
 if(b.op==='create'){if(!kinds.includes(b.kind))throw new Problem('Unknown game.');const name=str(b.name,2,40),id=crypto.randomUUID();const res=await db.prepare(`INSERT INTO game_rooms(id,name,kind,owner,state,created_at) SELECT ?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM game_rooms WHERE owner=?)<10 AND NOT EXISTS(SELECT 1 FROM game_rooms WHERE owner=? AND created_at>?)`).bind(id,name,b.kind,p.id,JSON.stringify(freshState(b.kind)),now,p.id,p.id,now-60000).run();if(!res.meta.changes)throw new Problem('Limit: 10 game rooms per account, one new room per minute.',429);return json({room:id});}
 const room=str(b.room,1,100),r=await roomData(room);
 if(b.op==='join'){await db.prepare('DELETE FROM game_players WHERE room_id=? AND seen_at<?').bind(room,now-75000).run();const existing=await db.prepare('SELECT slot FROM game_players WHERE room_id=? AND user_id=?').bind(room,p.id).first();if(!existing){const inserted=await db.prepare(`INSERT OR IGNORE INTO game_players(room_id,slot,user_id,seen_at,x,y) SELECT ?,CAST(value AS INTEGER),?,?,60+value*70,300+(value%3)*30 FROM json_each('[0,1,2,3,4,5,6,7,8,9]') WHERE value NOT IN(SELECT slot FROM game_players WHERE room_id=?) ORDER BY value LIMIT 1`).bind(room,p.id,now,room).run();if(!inserted.meta.changes)throw new Problem('Room full: maximum 10 people.',409);await db.prepare('DELETE FROM game_players WHERE user_id=? AND room_id!=?').bind(p.id,room).run();}await db.prepare('UPDATE game_players SET seen_at=? WHERE room_id=? AND user_id=?').bind(now,room,p.id).run();return json({ok:true});}
 if(b.op==='leave'){await db.prepare('DELETE FROM game_players WHERE room_id=? AND user_id=?').bind(room,p.id).run();return json({ok:true});}
 const mine=await member(room,p.id);let s=JSON.parse(r.state);
 if(b.op==='heartbeat'){const look=b.look||{},color=/^#[a-fA-F0-9]{6}$/.test(look.color)?look.color:'#74e4ba',hat=['none','crown','cap','wizard'].includes(look.hat)?look.hat:'none';await db.prepare('UPDATE game_players SET x=?,y=?,look=?,voice=?,seen_at=? WHERE room_id=? AND user_id=?').bind(Math.round(finite(b.x??mine.x,30,770)),Math.round(finite(b.y??mine.y,240,420)),JSON.stringify({color,hat}),b.voice===true?Number(b.epoch)||now:0,now,room,p.id).run();return json({ok:true});}
 if(b.op==='signal'){const target=str(b.target,1,200);const other=await member(room,target);if(!mine.voice||!other.voice)throw new Problem('Both players must enable voice first.',409);const payload=b.payload;if(!payload||!['offer','answer','ice'].includes(payload.type)||JSON.stringify(payload).length>16000)throw new Problem('Invalid voice signal.');await db.prepare('INSERT INTO voice_signals(room_id,sender,recipient,payload,created_at) VALUES(?,?,?,?,?)').bind(room,p.id,target,JSON.stringify({...payload,epoch:mine.voice,targetEpoch:other.voice}),now).run();await db.prepare('DELETE FROM voice_signals WHERE created_at<?').bind(now-120000).run();return json({ok:true});}
 if(b.op==='chat'){const text=str(b.text,1,1000);if(await db.prepare("SELECT 1 FROM game_events WHERE user_id=? AND kind='chat' AND created_at>? LIMIT 1").bind(p.id,now-800).first())throw new Problem('Wait a second between messages.',429);
 if(r.kind==='guess'&&s.drawer&&s.drawer!==p.id&&!s.revealed&&now-s.started<90000&&text.toLowerCase()===s.word.toLowerCase()){if(!s.solved.includes(p.id)){s.solved.push(p.id);s.scores[p.id]=(s.scores[p.id]||0)+10;s.scores[s.drawer]=(s.scores[s.drawer]||0)+5;await update(r,s);await event(room,p.id,'chat',{text:'Guessed the word! +10 points'});}return json({ok:true});}await event(room,p.id,'chat',{text});return json({ok:true});}
 if(b.op==='seat'){if(!['chess','checkers'].includes(r.kind))throw new Problem('Not a board game.');if(s.players.includes(p.id))return json({ok:true});if(s.players.length>=2)throw new Problem('Both seats are taken. You can spectate.',409);s.players.push(p.id);await update(r,s);return json({ok:true});}
 if(b.op==='release'){if(!['chess','checkers'].includes(r.kind))throw new Problem('Not a board game.');if(!s.players.includes(p.id))throw new Problem('You are not seated.',403);if(s.players.length===2&&!s.result&&!s.winner){if(r.kind==='chess')s.result=(s.players[0]===p.id?'Black':'White')+' wins by resignation';else s.winner=s.players[0]===p.id?2:1;}else s.players=s.players.filter((v:string)=>v!==p.id);await update(r,s);return json({ok:true});}
 if(b.op==='reset'){if(r.owner!==p.id)throw new Problem('Only the room host can reset the board.',403);s=freshState(r.kind);await update(r,s);return json({ok:true});}
 if(b.op==='move'){if(s.players.length!==2)throw new Problem('Waiting for a second player.',409);const at=s.players.indexOf(p.id);if(at<0)throw new Problem('Take a seat to play.',403);if(b.version!==r.version)throw new Problem('Board changed. Try your move again.',409);
 if(r.kind==='chess'){const c=chessPosition(s.moves);if(s.result||c.isGameOver())throw new Problem('Game finished. Ask the host for a new game.');if(c.turn()!==(at===0?'w':'b'))throw new Problem('It is the other player’s turn.');try{const move=c.move({from:str(b.from,2,2),to:str(b.to,2,2),promotion:['q','r','b','n'].includes(b.promotion)?b.promotion:'q'});s.moves.push(move.san);s.result=c.isCheckmate()?(c.turn()==='w'?'Black':'White')+' wins by checkmate':c.isGameOver()?'Draw':null;}catch{throw new Problem('That chess move is not legal.');}}
 else if(r.kind==='checkers'){if(s.turn!==at+1)throw new Problem('It is the other player’s turn.');try{s={...checkMove(s,finite(b.from,0,63),finite(b.to,0,63)),players:s.players}}catch(e){throw new Problem((e as Error).message)}}else throw new Problem('Not a board game.');await update(r,s);return json({ok:true});}
 if(b.op==='round'){if(r.kind!=='guess')throw new Problem('Not a guessing game.');if(r.owner!==p.id&&s.drawer!==p.id)throw new Problem('The host or current artist starts the next round.',403);const players=await all('SELECT user_id FROM game_players WHERE room_id=? AND seen_at>? ORDER BY slot',room,now-75000);if(players.length<2)throw new Problem('Bring at least two players for a round.');const current=players.findIndex(x=>x.user_id===s.drawer);s.drawer=players[(current+1)%players.length].user_id;s.word=words[crypto.getRandomValues(new Uint32Array(1))[0]%words.length];s.round++;s.started=now;s.solved=[];s.revealed=false;await update(r,s);await event(room,p.id,'clear',{});return json({ok:true});}
 if(b.op==='reveal'){if(r.kind!=='guess'||r.owner!==p.id&&s.drawer!==p.id)throw new Problem('Only host or artist can reveal.',403);s.revealed=true;await update(r,s);return json({ok:true});}
 if(b.op==='draw'||b.op==='undo'||b.op==='clear'){if(!['drawing','guess'].includes(r.kind))throw new Problem('This room has no canvas.');if(r.kind==='guess'&&(s.drawer!==p.id||s.revealed||now-s.started>90000))throw new Problem('Only the current artist can draw during the round.',403);
 if(b.op==='clear'){if(r.kind==='drawing'&&r.owner!==p.id)throw new Problem('Only host can clear the shared board.',403);await event(room,p.id,'clear',{});return json({ok:true});}
 if(b.op==='undo'){const id=finite(b.id,1,Number.MAX_SAFE_INTEGER);if(!await db.prepare("SELECT 1 FROM game_events WHERE id=? AND room_id=? AND user_id=? AND kind='draw'").bind(id,room,p.id).first())throw new Problem('You can only undo your own drawing.',403);await event(room,p.id,'undo',{id});return json({ok:true});}
 if(await db.prepare("SELECT COUNT(*) AS n FROM game_events WHERE room_id=? AND kind='draw'").bind(room).first<any>().then(v=>v.n>=5000))throw new Problem('This canvas is full. Create a new drawing room.');
 const d=b.drawing;if(!d||!['pen','line','rect','ellipse','text','eraser'].includes(d.tool)||!/^#[a-fA-F0-9]{6}$/.test(d.color))throw new Problem('Invalid drawing.');const width=finite(d.width,1,30),points=d.points;if(!Array.isArray(points)||!points.length||points.length>600)throw new Problem('Invalid stroke.');for(const pt of points){if(!Array.isArray(pt)||pt.length!==2)throw new Problem('Invalid point.');finite(pt[0],0,800);finite(pt[1],0,480)}await event(room,p.id,'draw',{tool:d.tool,color:d.color,width,points,text:d.tool==='text'?str(d.text,1,100):''});return json({ok:true});}
 throw new Problem('Unknown game action.',404);
 }catch(e){return problem(e)}}
