'use client';
import {useMemo,useRef,useState} from 'react';
export type GameEvent={id:number;user_id:string;kind:string;name:string;created_at:number;payload:any};
type Stroke={tool:string;color:string;width:number;points:number[][];text:string};
export function StrokeView({s}:{s:Stroke}){const p=s.points,a=p[0],b=p[p.length-1];if(!a)return null;const color=s.tool==='eraser'?'#fffdf6':s.color,props={stroke:color,strokeWidth:s.width,fill:'none',strokeLinecap:'round' as const,strokeLinejoin:'round' as const};if(s.tool==='text')return <text x={a[0]} y={a[1]} fill={s.color} fontSize={s.width+16} fontFamily="monospace">{s.text}</text>;if(s.tool==='rect')return <rect x={Math.min(a[0],b[0])} y={Math.min(a[1],b[1])} width={Math.abs(b[0]-a[0])} height={Math.abs(b[1]-a[1])} {...props}/>;if(s.tool==='ellipse')return <ellipse cx={(a[0]+b[0])/2} cy={(a[1]+b[1])/2} rx={Math.abs(b[0]-a[0])/2} ry={Math.abs(b[1]-a[1])/2} {...props}/>;if(s.tool==='line')return <line x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} {...props}/>;if(p.length===1)return <circle cx={a[0]} cy={a[1]} r={s.width/2} fill={color}/>;let path=`M ${a.join(' ')}`;for(let i=1;i<p.length-1;i++)path+=` Q ${p[i].join(' ')} ${(p[i][0]+p[i+1][0])/2} ${(p[i][1]+p[i+1][1])/2}`;path+=` L ${b.join(' ')}`;return <path d={path} {...props}/>}
export default function DrawingBoard({events,uid,canDraw,host,send}:{events:GameEvent[];uid:string;canDraw:boolean;host:boolean;send:(op:string,data?:any)=>Promise<any>}){const[tool,setTool]=useState('pen'),[color,setColor]=useState('#263148'),[width,setWidth]=useState(4),[text,setText]=useState(''),[preview,setPreview]=useState<Stroke|null>(null),[busy,setBusy]=useState(false);const current=useRef<Stroke|null>(null),canvas=useRef<SVGSVGElement>(null);const strokes=useMemo(()=>{let map=new Map<number,GameEvent>();for(const e of events){if(e.kind==='clear')map.clear();if(e.kind==='draw')map.set(e.id,e);if(e.kind==='undo')map.delete(e.payload.id);}return [...map.values()]},[events]);
 function point(e:React.PointerEvent){const box=canvas.current!.getBoundingClientRect();return [Math.max(0,Math.min(800,(e.clientX-box.left)*800/box.width)),Math.max(0,Math.min(480,(e.clientY-box.top)*480/box.height))]}
 function start(e:React.PointerEvent<SVGSVGElement>){if(!canDraw||busy||tool==='text'&&!text.trim())return;e.currentTarget.setPointerCapture(e.pointerId);current.current={tool,color,width,points:[point(e)],text};setPreview({...current.current})}
 function move(e:React.PointerEvent){const s=current.current;if(!s)return;const next=point(e);if(s.tool==='pen'||s.tool==='eraser'){const last=s.points.at(-1)!;if(Math.hypot(next[0]-last[0],next[1]-last[1])<2)return;if(s.points.length>=590)return;s.points.push(next)}else s.points=[s.points[0],next];setPreview({...s,points:[...s.points]})}
 async function end(){if(!current.current)return;const s=current.current;current.current=null;setBusy(true);try{await send('draw',{drawing:s})}finally{setBusy(false);setPreview(null)}}
 const own=strokes.filter(s=>s.user_id===uid).at(-1);
 return <div className="drawing-panel"><div className="draw-tools"><label>Tool<select value={tool} onChange={e=>setTool(e.target.value)} disabled={!canDraw}>{[['pen','Freehand / curves'],['line','Straight line'],['rect','Rectangle'],['ellipse','Ellipse'],['text','Text'],['eraser','Eraser']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Ink<input type="color" value={color} onChange={e=>setColor(e.target.value)} disabled={!canDraw}/></label><label>Size<input type="range" min={1} max={30} value={width} onChange={e=>setWidth(Number(e.target.value))} disabled={!canDraw}/></label><button className="secondary" disabled={!canDraw||!own||busy} onClick={()=>send('undo',{id:own?.id})}>Undo mine</button>{host&&<button className="secondary" disabled={busy} onClick={()=>send('clear')}>Clear canvas</button>}</div>{tool==='text'&&<label className="canvas-text">Text to place<input value={text} onChange={e=>setText(e.target.value)} maxLength={100} placeholder="Type, then tap the canvas"/></label>}<svg ref={canvas} className={`drawing-canvas ${canDraw?'can-draw':''}`} viewBox="0 0 800 480" role="img" aria-label="Shared drawing canvas" onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{current.current=null;setPreview(null)}}><rect width={800} height={480} fill="#fffdf6"/>{strokes.map(e=><StrokeView key={e.id} s={e.payload}/>)}{preview&&<StrokeView s={preview}/>}</svg><p className="game-tip">{canDraw?'Drag to draw. Pick shapes or type a label and tap to place it. Undo removes your own last stroke.':'Watching the artist. Send your guesses in the room chat.'} {busy?'Saving stroke…':''}</p></div>}
