import {Chess} from 'chess.js';
export type CheckState={board:number[];turn:1|2;forced:number|null;winner:number|null};
export function freshCheckers():CheckState{return {board:Array.from({length:64},(_,i)=>((Math.floor(i/8)+i%8)%2===1?(i<24?2:i>=40?1:0):0)),turn:1,forced:null,winner:null}}
function options(s:CheckState,at:number,capture:boolean){const piece=s.board[at];if(!piece||piece%10!==s.turn)return [];const r=Math.floor(at/8),c=at%8,directions=piece>=10?[-1,1]:[s.turn===1?-1:1],moves:number[]=[];for(const dr of directions)for(const dc of [-1,1]){const nr=r+dr*(capture?2:1),nc=c+dc*(capture?2:1);if(nr<0||nr>7||nc<0||nc>7||s.board[nr*8+nc])continue;if(capture){const middle=s.board[(r+dr)*8+c+dc];if(!middle||middle%10===s.turn)continue}moves.push(nr*8+nc)}return moves}
export function checkerMoves(s:CheckState,at:number){if(s.winner||s.forced!==null&&s.forced!==at)return [];const any=s.board.some((_,i)=>options(s,i,true).length);return options(s,at,any)}
export function checkMove(s:CheckState,from:number,to:number):CheckState{if(!checkerMoves(s,from).includes(to))throw new Error('That checker move is not legal. Captures are required.');const n:CheckState={...s,board:[...s.board]},r=Math.floor(from/8),nr=Math.floor(to/8),jump=Math.abs(nr-r)===2;let piece=n.board[from];n.board[from]=0;if(jump)n.board[(r+nr)/2*8+(from%8+to%8)/2]=0;const crowned=piece<10&&(nr===0&&piece===1||nr===7&&piece===2);if(crowned)piece+=10;n.board[to]=piece;if(jump&&!crowned&&options(n,to,true).length){n.forced=to;return n}n.turn=n.turn===1?2:1;n.forced=null;if(!n.board.some((_,i)=>checkerMoves(n,i).length))n.winner=s.turn;return n}
export function chessPosition(moves:string[]){const c=new Chess();for(const m of moves)c.move(m);return c}
export const words=['sunflower','spaceship','penguin','bicycle','castle','watermelon','umbrella','volcano','robot','dragon','pizza','octopus','snowman','lighthouse','butterfly','telescope','rocket','rainbow','island','guitar'];
export function freshState(kind:string){return kind==='chess'?{moves:[],players:[],result:null}:kind==='checkers'?{...freshCheckers(),players:[]}:kind==='guess'?{drawer:null,word:'',round:0,started:0,solved:[],scores:{},revealed:false}:{}}
