'use client';
import {useEffect,useRef,useState} from 'react';
type Player={user_id:string;voice:number;name:string};
type Signal={id:number;sender:string;payload:any};
type Peer={pc:RTCPeerConnection;epoch:number;audio:HTMLAudioElement;queue:RTCIceCandidateInit[]};
export function useVoice(room:string,uid:string,signal:(target:string,payload:any)=>Promise<any>){const [enabled,setEnabled]=useState(false),[status,setStatus]=useState('Microphone off'),[epoch,setEpoch]=useState(0);const stream=useRef<MediaStream|null>(null),peers=useRef(new Map<string,Peer>()),alive=useRef(true),enabledRef=useRef(false),epochRef=useRef(0),sendRef=useRef(signal);sendRef.current=signal;
 function close(id:string){const peer=peers.current.get(id);if(peer){peer.pc.close();peer.audio.srcObject=null;peer.audio.remove();peers.current.delete(id)}}
 function stop(){enabledRef.current=false;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;for(const id of peers.current.keys())close(id);if(alive.current){setEnabled(false);setEpoch(0);setStatus('Microphone off')}}
 async function toggle(){if(enabledRef.current){stop();return}setStatus('Requesting microphone…');try{const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(!alive.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;enabledRef.current=true;epochRef.current=Date.now();setEpoch(epochRef.current);setEnabled(true);setStatus('Voice enabled · connecting to room')}catch(e){setStatus((e as Error).name==='NotAllowedError'?'Microphone permission denied. Text chat still works.':'Microphone unavailable. Text chat still works.')}}
 function make(id:string,remoteEpoch:number){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]}),audio=document.createElement('audio');audio.autoplay=true;audio.setAttribute('playsinline','');const peer={pc,epoch:remoteEpoch,audio,queue:[]};peers.current.set(id,peer);stream.current?.getTracks().forEach(t=>pc.addTrack(t,stream.current!));pc.onicecandidate=e=>{if(e.candidate)sendRef.current(id,{type:'ice',candidate:e.candidate.toJSON()}).catch(()=>{})};pc.ontrack=e=>{audio.srcObject=e.streams[0]||new MediaStream([e.track]);audio.play().catch(()=>{if(alive.current)setStatus('Tap Enable sound to hear the room.')})};pc.onconnectionstatechange=()=>{if(!alive.current)return;if(pc.connectionState==='connected')setStatus('Voice connected');if(pc.connectionState==='failed')setStatus('Voice could not connect on this network. Text chat is available.')};return peer}
 async function sync(players:Player[],signals:Signal[]){if(!enabledRef.current)return;const remote=players.filter(p=>p.user_id!==uid&&p.voice);for(const [id,peer] of peers.current)if(!remote.some(p=>p.user_id===id&&p.voice===peer.epoch))close(id);for(const p of remote){if(!peers.current.has(p.user_id)&&uid<p.user_id){const peer=make(p.user_id,p.voice);try{const offer=await peer.pc.createOffer();await peer.pc.setLocalDescription(offer);await sendRef.current(p.user_id,{type:'offer',sdp:offer.sdp});}catch{close(p.user_id);if(alive.current)setStatus('Waiting for voice peers…')}}}
 for(const msg of signals){const other=remote.find(p=>p.user_id===msg.sender),d=msg.payload;if(!other||d.epoch!==other.voice||d.targetEpoch!==epochRef.current)continue;let peer=peers.current.get(msg.sender);if(!peer)peer=make(msg.sender,other.voice);try{if(d.type==='offer'){await peer.pc.setRemoteDescription({type:'offer',sdp:d.sdp});for(const c of peer.queue)await peer.pc.addIceCandidate(c);peer.queue=[];const answer=await peer.pc.createAnswer();await peer.pc.setLocalDescription(answer);await sendRef.current(msg.sender,{type:'answer',sdp:answer.sdp});}else if(d.type==='answer'){await peer.pc.setRemoteDescription({type:'answer',sdp:d.sdp});for(const c of peer.queue)await peer.pc.addIceCandidate(c);peer.queue=[];}else if(d.type==='ice'){if(peer.pc.remoteDescription)await peer.pc.addIceCandidate(d.candidate);else peer.queue.push(d.candidate)}}catch{if(alive.current)setStatus('Voice connection is retrying. Text chat still works.')}}}
 function resume(){for(const p of peers.current.values())p.audio.play().catch(()=>{});setStatus('Sound enabled')}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;stop()}},[room]);return {enabled,epoch,status,toggle,sync,resume};}
